### ISSUE TITLE
Tokenの有効期限は必要なのか

### ISSUE THREAD

**Issue by Cj-bc** [Sakuten/lottery-backend#12]
https://github.com/Sakuten/lottery-backend/blob/develop/api/routes/auth.py#L27
及び
https://github.com/Sakuten/lottery-backend/blob/develop/api/auth.py#L9
で使われている `generate_token`メゾットにて、Tokenの有効期限としてexpirationを返していると思うのですが、必要ないのではないでしょうか。
この前の会議にて、Tokenの有効期限は設定せず、全体が終了後に失効させるということに決まったからです。

**Comment by coord-e** [comment]
はい。(全肯定)

2018/06/14 8:36、Cj-bc <notifications@github.com>のメール:

**Comment by Cj-bc** [comment]
これ、フロントの方も関わって来るのだろうか...
一応`git grep`かけて、"expiration"キーワードは存在しない確認はしましたがどうですか。
フロントで、Tokenの期限チェックなどしているならそこも消さないとエラーになると思うので...

**Comment by coord-e** [comment]
フロントでそれはよくないですのでやっていません
PRs are welcome. Thanks

**Comment by coord-e** [comment]
#13

**Comment by Cj-bc** [comment]
mergeされていたのに気がついたので閉じます。
