### ISSUE TITLE
いつ開発が始められるようになったのかわかりにくい

### ISSUE THREAD

**Issue by coord-e** [Sakuten/lottery-backend#14]
なんかわかりやすいメッセージを出しましょう

**Comment by Cj-bc** [comment]
[sakuten/devenv](https://github.com/Sakuten/devenv) で扱うないような気がしますので開き直しますね

**Comment by coord-e** [comment]
いやそれが、これ実装するのはバックエンド側なんです

**Comment by Cj-bc** [comment]
あっそうなのごめん...

**Comment by Cj-bc** [comment]
普通にメッセージを表示するか、バナーを表示するかするといいのではないですかね
`====== System Ready. Please connect to localhost:8000 ======`
とか
```
==== バナー書くのめんd
====
====
```
とか（転載です

**Comment by coord-e** [comment]
やります

**Comment by coord-e** [comment]
マージしました
